
- name: "extract deploy and start backend" 
  become: true 
  shell: echo "extract"

- name: "copy over artifact"
  become: true 
  copy:
    src: ~/project/artifact.tar.gz
    dest: ./artifact.tar.gz

- name: "extract the zipped artifact"
  become: true  
  shell: | 
    tar xzvf artifact.tar.gz 


- name : "start server"    
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
